from enum import Enum, auto


class Event(Enum):
    START_CHAT = auto()
    DIAGNOSA = auto()
    SERVIS = auto()
    TIPS = auto()
    MOTOR = auto()
    MOBIL = auto()
    MESIN = auto()
    KELISTRIKAN = auto()
    REM = auto()
    BAN = auto()
    OLI = auto()
    AKI = auto()
    TRANSMISI = auto()
    SUSPENSI = auto()
    PENDINGIN = auto()
    YA = auto()
    TIDAK = auto()
    MILEAGE_5000 = auto()
    MILEAGE_10000 = auto()
    MILEAGE_15000 = auto()
    MILEAGE_20000 = auto()
    MILEAGE_25000 = auto()
    MENU = auto()
    SELESAI = auto()
    UNKNOWN = auto()
