from automata.states import State
from automata.events import Event

TRANSITION_TABLE: dict[tuple[State, Event], State] = {
    # ── START ──
    (State.START, Event.START_CHAT): State.WELCOME,

    # ── WELCOME -> module selection ──
    (State.WELCOME, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.WELCOME, Event.SERVIS): State.SERVICE_START,
    (State.WELCOME, Event.TIPS): State.MAINTENANCE_VEHICLE,

    # ── DIAGNOSIS -> vehicle type ──
    (State.DIAGNOSIS_START, Event.MOTOR): State.SELECT_MOTOR_SYMPTOM,
    (State.DIAGNOSIS_START, Event.MOBIL): State.SELECT_MOBIL_SYMPTOM,

    # ── DIAGNOSIS -> symptom selection (motor) ──
    (State.SELECT_MOTOR_SYMPTOM, Event.MESIN): State.MOTOR_ENGINE,
    (State.SELECT_MOTOR_SYMPTOM, Event.KELISTRIKAN): State.MOTOR_ELECTRICAL,
    (State.SELECT_MOTOR_SYMPTOM, Event.AKI): State.MOTOR_ELECTRICAL,
    (State.SELECT_MOTOR_SYMPTOM, Event.REM): State.MOTOR_BRAKE,
    (State.SELECT_MOTOR_SYMPTOM, Event.BAN): State.MOTOR_TIRE,
    (State.SELECT_MOTOR_SYMPTOM, Event.TRANSMISI): State.MOTOR_TRANSMISI,
    (State.SELECT_MOTOR_SYMPTOM, Event.SUSPENSI): State.MOTOR_SUSPENSI,
    (State.SELECT_MOTOR_SYMPTOM, Event.PENDINGIN): State.MOTOR_PENDINGIN,

    # ── DIAGNOSIS -> symptom selection (mobil) ──
    (State.SELECT_MOBIL_SYMPTOM, Event.MESIN): State.MOTOR_ENGINE,
    (State.SELECT_MOBIL_SYMPTOM, Event.KELISTRIKAN): State.MOTOR_ELECTRICAL,
    (State.SELECT_MOBIL_SYMPTOM, Event.AKI): State.MOTOR_ELECTRICAL,
    (State.SELECT_MOBIL_SYMPTOM, Event.REM): State.MOTOR_BRAKE,
    (State.SELECT_MOBIL_SYMPTOM, Event.BAN): State.MOTOR_TIRE,
    (State.SELECT_MOBIL_SYMPTOM, Event.TRANSMISI): State.MOTOR_TRANSMISI,
    (State.SELECT_MOBIL_SYMPTOM, Event.SUSPENSI): State.MOTOR_SUSPENSI,
    (State.SELECT_MOBIL_SYMPTOM, Event.PENDINGIN): State.MOTOR_PENDINGIN,

    # ── DIAGNOSIS -> engine questions ──
    (State.MOTOR_ENGINE, Event.YA): State.ENGINE_Q2,
    (State.MOTOR_ENGINE, Event.TIDAK): State.ENGINE_Q3,
    (State.ENGINE_Q2, Event.YA): State.RESULT_ENGINE_MINOR,
    (State.ENGINE_Q2, Event.TIDAK): State.RESULT_ENGINE_MAJOR,
    (State.ENGINE_Q3, Event.YA): State.RESULT_BATTERY_CHECK,
    (State.ENGINE_Q3, Event.TIDAK): State.RESULT_BATTERY_WEAK,

    # ── DIAGNOSIS -> one-question results ──
    (State.MOTOR_ELECTRICAL, Event.YA): State.RESULT_ELECTRICAL,
    (State.MOTOR_ELECTRICAL, Event.TIDAK): State.RESULT_ELECTRICAL,
    (State.MOTOR_BRAKE, Event.YA): State.RESULT_BRAKE,
    (State.MOTOR_BRAKE, Event.TIDAK): State.RESULT_BRAKE,
    (State.MOTOR_TIRE, Event.YA): State.RESULT_TIRE,
    (State.MOTOR_TIRE, Event.TIDAK): State.RESULT_TIRE,
    (State.MOTOR_TRANSMISI, Event.YA): State.RESULT_TRANSMISI,
    (State.MOTOR_TRANSMISI, Event.TIDAK): State.RESULT_TRANSMISI,
    (State.MOTOR_SUSPENSI, Event.YA): State.RESULT_SUSPENSI,
    (State.MOTOR_SUSPENSI, Event.TIDAK): State.RESULT_SUSPENSI,
    (State.MOTOR_PENDINGIN, Event.YA): State.RESULT_PENDINGIN,
    (State.MOTOR_PENDINGIN, Event.TIDAK): State.RESULT_PENDINGIN,

    # ── SERVICE -> vehicle type ──
    (State.SERVICE_START, Event.MOTOR): State.MOTOR_MILEAGE,
    (State.SERVICE_START, Event.MOBIL): State.MOBIL_MILEAGE,

    # ── SERVICE -> mileage selection ──
    (State.MOTOR_MILEAGE, Event.MILEAGE_5000): State.SERVICE_5000,
    (State.MOTOR_MILEAGE, Event.MILEAGE_10000): State.SERVICE_10000,
    (State.MOTOR_MILEAGE, Event.MILEAGE_15000): State.SERVICE_15000,
    (State.MOTOR_MILEAGE, Event.MILEAGE_20000): State.SERVICE_20000,
    (State.MOTOR_MILEAGE, Event.MILEAGE_25000): State.SERVICE_25000,
    (State.MOBIL_MILEAGE, Event.MILEAGE_5000): State.SERVICE_5000,
    (State.MOBIL_MILEAGE, Event.MILEAGE_10000): State.SERVICE_10000,
    (State.MOBIL_MILEAGE, Event.MILEAGE_15000): State.SERVICE_15000,
    (State.MOBIL_MILEAGE, Event.MILEAGE_20000): State.SERVICE_20000,
    (State.MOBIL_MILEAGE, Event.MILEAGE_25000): State.SERVICE_25000,

    # ── MAINTENANCE -> vehicle type ──
    (State.MAINTENANCE_VEHICLE, Event.MOTOR): State.MAINTENANCE_START,
    (State.MAINTENANCE_VEHICLE, Event.MOBIL): State.MAINTENANCE_START,

    # ── MAINTENANCE -> topic selection ──
    (State.MAINTENANCE_START, Event.MESIN): State.TIPS_ENGINE,
    (State.MAINTENANCE_START, Event.OLI): State.TIPS_OIL,
    (State.MAINTENANCE_START, Event.AKI): State.TIPS_BATTERY,
    (State.MAINTENANCE_START, Event.REM): State.TIPS_BRAKE,
    (State.MAINTENANCE_START, Event.BAN): State.TIPS_TIRE,
    (State.MAINTENANCE_START, Event.TRANSMISI): State.TIPS_TRANSMISI,
    (State.MAINTENANCE_START, Event.SUSPENSI): State.TIPS_SUSPENSI,
    (State.MAINTENANCE_START, Event.PENDINGIN): State.TIPS_PENDINGIN,

    # ── FROM RESULT STATES -> re-enter modules ──
    (State.RESULT_ENGINE_MINOR, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_ENGINE_MINOR, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_ENGINE_MINOR, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_ENGINE_MAJOR, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_ENGINE_MAJOR, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_ENGINE_MAJOR, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_BATTERY_CHECK, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_BATTERY_CHECK, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_BATTERY_CHECK, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_BATTERY_WEAK, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_BATTERY_WEAK, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_BATTERY_WEAK, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_ELECTRICAL, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_ELECTRICAL, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_ELECTRICAL, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_BRAKE, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_BRAKE, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_BRAKE, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_TIRE, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_TIRE, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_TIRE, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_TRANSMISI, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_TRANSMISI, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_TRANSMISI, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_SUSPENSI, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_SUSPENSI, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_SUSPENSI, Event.TIPS): State.MAINTENANCE_START,
    (State.RESULT_PENDINGIN, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.RESULT_PENDINGIN, Event.SERVIS): State.SERVICE_START,
    (State.RESULT_PENDINGIN, Event.TIPS): State.MAINTENANCE_START,

    # ── FROM SERVICE RESULT STATES -> re-enter modules ──
    (State.SERVICE_5000, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.SERVICE_5000, Event.SERVIS): State.SERVICE_START,
    (State.SERVICE_5000, Event.TIPS): State.MAINTENANCE_START,
    (State.SERVICE_10000, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.SERVICE_10000, Event.SERVIS): State.SERVICE_START,
    (State.SERVICE_10000, Event.TIPS): State.MAINTENANCE_START,
    (State.SERVICE_15000, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.SERVICE_15000, Event.SERVIS): State.SERVICE_START,
    (State.SERVICE_15000, Event.TIPS): State.MAINTENANCE_START,
    (State.SERVICE_20000, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.SERVICE_20000, Event.SERVIS): State.SERVICE_START,
    (State.SERVICE_20000, Event.TIPS): State.MAINTENANCE_START,
    (State.SERVICE_25000, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.SERVICE_25000, Event.SERVIS): State.SERVICE_START,
    (State.SERVICE_25000, Event.TIPS): State.MAINTENANCE_START,

    # ── FROM TIPS RESULT STATES -> re-enter modules ──
    (State.TIPS_ENGINE, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_ENGINE, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_ENGINE, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_OIL, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_OIL, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_OIL, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_BATTERY, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_BATTERY, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_BATTERY, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_BRAKE, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_BRAKE, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_BRAKE, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_TIRE, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_TIRE, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_TIRE, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_TRANSMISI, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_TRANSMISI, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_TRANSMISI, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_SUSPENSI, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_SUSPENSI, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_SUSPENSI, Event.TIPS): State.MAINTENANCE_START,
    (State.TIPS_PENDINGIN, Event.DIAGNOSA): State.DIAGNOSIS_START,
    (State.TIPS_PENDINGIN, Event.SERVIS): State.SERVICE_START,
    (State.TIPS_PENDINGIN, Event.TIPS): State.MAINTENANCE_START,
}


def get_next_state(current: State, event: Event) -> State | None:
    return TRANSITION_TABLE.get((current, event))
